export const Data=[
    {
        "id":1,
        "akronim":"AZC",
        "aciqlama":"Azercosmos",
        "missiya":"hdhdkejf"
    },
    {
        "id":2,
        "akronim":"ITRI",
        "aciqlama":"Socar Information",
        "missiya":"hdhdkcdfejf"
    },
    {
        "id":3,
        "akronim":"AZE",
        "aciqlama":"Azerbaijan",
        "missiya":"hdhdsfekejf"
    },
    {
        "id":4,
        "akronim":"ABB",
        "aciqlama":"Azerbaycan beynexalq",
        "missiya":"hdhdsdfasfkejf"
    },
    {
        "id":5,
        "akronim":"KPT",
        "aciqlama":"kapital",
        "missiya":"hdhefefdkejf"
    },
    {
        "id":6,
        "akronim":"PRTU",
        "aciqlama":"kapitddhdl",
        "missiya":"hdhefefdkejf"
    },
    {
        "id":7,
        "akronim":"HJAS",
        "aciqlama":"hghjapital",
        "missiya":"hdhefefdkejf"
    },
    {
        "id":8,
        "akronim":"ICUY",
        "aciqlama":"ncndncdc",
        "missiya":"hdhefefdkejf"
    }
]